# Основные настройки
base_url: "https://vnexpress.net" # Убедитесь, что эта строка присутствует и правильно написана
category_path: "/thoi-su" 
output_filename: "vnexpress_articles.json"
request_delay_seconds: 2
request_timeout_seconds: 10
max_pages_to_scrape: 2

# Селекторы для парсинга (ОЧЕНЬ ВАЖНО: АДАПТИРУЙТЕ ИХ ПОД АКТУАЛЬНУЮ СТРУКТУРУ VNEXPRESS)
selectors:
  article_link_selector: ".item_list_news .title_news a, .item-news h3 a"
  article_title_class: "title-detail"
  article_date_class: "date"
  article_author_class: "author_name"
  article_content_class: "fck_detail"
  pagination_next_selector: "a.btn-next, .pagination-next a"
