name: Run VnExpress Scraper

on:
  schedule:
    # Запускать каждый день в 00:00 UTC
    # Вы можете настроить расписание по своему усмотрению (например, каждые 12 часов)
    - cron: '0 0 * * *' 
  workflow_dispatch: # Позволяет запускать вручную из интерфейса GitHub Actions

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python vnexpress_parser.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add vnexpress_articles.json vnexpress_parser.log
        git commit -m "Automated: Update VnExpress articles" || echo "No changes to commit"
        git push origin main || echo "No new data to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
