# Основные настройки
base_url: "https://vnexpress.net"
category_path: "/thoi-su" # Пример: категория "Общество"
output_filename: "vnexpress_articles.json"
request_delay_seconds: 5 # Увеличена задержка между запросами для снижения вероятности блокировки
request_timeout_seconds: 10 # Таймаут для HTTP-запросов
max_pages_to_scrape: 2   # Максимальное количество страниц для парсинга (установите больше для полного парсинга)

# Селекторы для парсинга (ОЧЕНЬ ВАЖНО: АДАПТИРУЙТЕ ИХ ПОД АКТУАЛЬНУЮ СТРУКТУРУ VNEXPRESS)
# Используйте инструменты разработчика в браузере (F12), чтобы найти правильные селекторы.
selectors:
  # CSS-селектор для ссылок на статьи на странице категории/списка
  # Пример: может быть несколько вариантов, например, для главной ленты и для боковых блоков.
  # Возможно, понадобится более специфичный селектор.
  article_link_selector: ".item_list_news .title_news a, .item-news h3 a"

  # Классы HTML-элементов для извлечения данных из самой статьи
  # (В Beautiful Soup `find` с `class_` ищет по классу)
  article_title_class: "title-detail" # Класс для <h1> заголовка статьи
  article_date_class: "date"          # Класс для <span> даты публикации
  article_author_class: "author_name" # Класс для <p> автора (если есть). Может быть "author" или отсутствовать.
  article_content_class: "fck_detail" # Класс для <article> или <div> с основным содержанием статьи.

  # CSS-селектор для ссылки на следующую страницу пагинации
  # Пример: `.pagination a.btn-next` или `.page_nav .next_page a`
  pagination_next_selector: "a.btn-next, .pagination-next a"
